version: '3.8'

services:
  web:
    build:
      context: .  # pasta onde está o Dockerfile.local
      dockerfile: docker/Dockerfile.local
    ports:
      - "8000:8000"
    volumes:
      - ./main.py:/app/main.py  # (opcional, útil para desenvolvimento)
